### PR TITLE
Update $.js

### PR DESCRIPTION
**Pull request by alphons**
Dont forget prop.js for making dist

### CODE REVIEW

**Comment by stefangabos** [comment]
there's more work to be done with `prop`, it's not just another `attr`
i've looked at [zepto](https://zeptojs.com/zepto.js)'s source (search for `prop: function`)

**Comment by stefangabos** [comment]
also, the [jQuery documentation](https://api.jquery.com/prop/) has more info about this

**Comment by alphons** [comment]
I think 99% of prop implementation works, tested against jquery.
prop( propertyName ) 100%
.prop( propertyName, value ) 100%
.prop( properties ) 100%
.prop( propertyName, function ) // 99% only arguments missing, call does work!!
Usage of prop / function is minimal, there are far better ways of doing this.
Difference between attr and prop is evident, test it yourself, when changing text input
$("#Output1").text( $("#MyInput").attr("value") );
$("#Output2").text( $("#MyInput").prop("value") );

**Comment by stefangabos** [comment]
`value` is a particular example. look at [jQuery's source](https://github.com/jquery/jquery/blob/master/src/attributes/prop.js) which also uses a white list of properties

**Comment by alphons** [comment]
Thats the reason why jQuery got that big!!! :(

With my modifications zebra is getting more compatible with the original jquery basics.
Without my modifications, zebra is of no use.
However, thanks you for the initial base.

**Comment by stefangabos** [comment]
thank **you** for the contributions

**Pull request closed without merging**
